version: 2
updates:
  - package-ecosystem: npm
    directory: /
    versioning-strategy: increase
    schedule:
      interval: weekly
      day: "thursday"
      time: "11:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 15
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "08:30"
      timezone: Asia/Tokyo
