name: GitHub Workflow Metrics
description: TODO
inputs:
  range:
    description: |
      The range of time to measure the workflows.
      This can be:
      7days, 14days, 30days
    required: false
    default: 30days
  aggregate:
    description: |
      Determines how the workflow metrics should be aggregated.
      This can be:
      average, median, min, max
    required: false
    default: average
  only:
    description: Only the specified workflows will be measured. This is supposed to be comma-separated list
    required: false
    default: ""
  status:
    description: |
      Only the workflows with the specified status will be measured.
      This can be:
      completed, action_required, cancelled, failure, neutral,
      skipped, stale, success, timed_out, in_progress, queued,
      requested, waiting, pending
    required: false
    default: ""
  label:
    description: The label for GitHub issues that the GitHub Action creates
    required: false
    default: github-workflows-metrics
  token:
    description: The GitHub token used to create an authenticated client
    required: false
    default: ${{ github.token }}
branding:
  icon: bar-chart
  color: gray-dark
runs:
  using: node20
  main: dist/index.js
