name: GitHub Workflow Metrics
description: TODO
inputs:
  only:
    description: Only the specified workflows will be measured. This is supposed to be comma-separated list
    required: false
    default: ""
  label:
    description: The label for GitHub issues that the GitHub Action creates
    required: false
    default: github-workflows-metrics
  token:
    description: The GitHub token used to create an authenticated client
    required: false
    default: ${{ github.token }}
branding:
  icon: stop-circle
  color: yellow
runs:
  using: node20
  main: dist/index.js
