name: GitHub Workflows Metrics
on:
  workflow_dispatch:
permissions:
  actions: read
  issues: write
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: yykamei/github-workflows-metrics@a109aa06b57f7b3c81432ab4a1e9ea4e4cc1f6a6 # main
        with:
          only: ci.yml
          status: success
