name: GitHub Workflow Metrics
on:
  workflow_dispatch:
permissions:
  contents: read # actions/checkout requires this permission
  actions: read
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
